[Init]
# place icon in /usr/share/icons/hicolor/scalable/apps/
Icon=proc-mon-hex-white-blue

[Obsidian Vault]
Command=rclone mount google-drive:/Code/Projects/ObsidianVault ~/Documents/ObsidianVault
Autostart=true
